### ISSUE TITLE
.similarity 返回数值全部为0

### ISSUE THREAD

**Issue by xikakera** [norybaby/cilin_similarity#1]
您好!
  我使用这个库,用python调用测试cilin_call.py,返回的scope全是0
  请问 这个该怎么修改? 或者说我环境有问题?
  是python 调用 C++的时候中文传递参数有错?

**Comment by xikakera** [comment]
您好!
  我的环境是 python 3.5
 得出解决方法:
  
  #line 6

   cilin_lib.read_cilin('cilin.txt'.encode('UTF-8'))

  #line 14

    print (w,cilin_lib.similarity(p_word.encode('UTF-8'),w.encode('UTF-8')))

**Comment by norybaby** [comment]
ok,谢谢使用。
原来的测试代码是pyhon2.7上的。
